RazorPDFExample/Controllers/PdfSampleController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using RazorPDF;
using RazorPDFExample.Models;

namespace RazorPDFExample.Controllers
{
    public class PdfSampleController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public PdfResult Pdf()
        {
            // With no Model and default view name.  Pdf is always the default view name
            return new PdfResult();
        }

        public ActionResult PdfModel(string id)
        {
            // Since type is an ActionResult, we can still return an html view if something isn't right
            if (id != "yoda")
                return View("NotFound");

            // get Person
            var person = new Person { UserName = id, LuckyNumber = 7 };

            // pass in Model, then View name
            var pdf = new PdfActionResult("HtmlToPdf", person);

            // Add to the view bag
            // pdf.ViewBag.Title = "Title from ViewBag";

            return pdf;
        }

        public ActionResult PdfTake3(string id)
        {
            var person = new Person() { UserName = id, LuckyNumber = 17 };

            // return new PdfResult(person, "PdfModel");
            return new PdfActionResult("HtmlToPdf", person);
        }

        public ActionResult HtmlReport()
        {
            // Setup sample model
            var list = new List<Person>();
            for (int i = 1; i < 10; i++)
                list.Add(new Person() { UserName = "Person " + i, LuckyNumber = i });

            // Output to Pdf?
            if (Request.QueryString["format"] == "pdf")
            {
                return new PdfResult(list, "HtmlReport");
            }


            return View(list);
        }

        public ActionResult ReportSample()
        {
            var list = new List<Person>();

            for (int i = 1; i < 10; i++)
                list.Add(new Person() { UserName = "Person " + i.ToString(), LuckyNumber = i });

            var pdf = new PdfResult(list, "ReportSample");
            pdf.ViewBag.Title = "Report Title";

            return pdf;
        }
    }
}

RazorPDFExample/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Not Found</h2>

RazorPDFExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("PDF Samples", "Index", "PdfSample")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

RazorPDFExample/Views/Shared/_PdfHtmlLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>RazorPDF</title>
    <style>
        html {
            font-family: Arial;
        }

        h1 {
            color: blue;
        }

        table {
            border: 1px solid black;
            border-spacing: 0px;
        }

            table tr th {
                background-color: gray;
                color: white;
                padding: 2px;
            }

            table tr td {
                margin: 0px;
                padding: 2px;
            }
    </style>
</head>
<body>
    @RenderBody()
</body>
</html>

RazorPDFExample/Views/Shared/_PdfLayout.cshtml
<?xml version="1.0" encoding="UTF-8" ?>
<itext creationdate="@DateTime.Now.ToString()" producer="RazorPDF">
    @RenderBody()
</itext>